# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_remove_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
