# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validation', '0008_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('sphone', models.CharField(max_length=20)),
                ('pphone', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=100)),
                ('emailadd', models.CharField(max_length=100)),
                ('classx', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('potrait', models.ImageField(upload_to='upload/img/%Y/%m/%d')),
            ],
        ),
    ]
